### ISSUE TITLE
Separate Backends

### ISSUE THREAD

**Issue by pabloguarneros** [Phil-Barv/demoapp#10]
Currently, there are two backends in the application. The two directories are "backend" and "backend-signup and login." Although I understand these are two separate implementations of the backend done by different people, why do we have them both within the same folder?  Is there a particular software dev best practices reason for doing this?

Each of the folders has a database included. The "backend-signup and login" runs in Python 3.9 whereas the normal backend runs in 3.6.

**Comment by Phil-Barv** [comment]
@pabloguarneros seems like an integration issue, they should be running from the same folder. Also, I agree we should lock the python version.


Update: Working on resolving the two backend issue.
