### ISSUE TITLE
Python Versions

### ISSUE THREAD

**Issue by pabloguarneros** [Phil-Barv/demoapp#11]
When running different branches, the library versions keep changing. Even if a branch supplied a requirement.txt file detailing their current pip environment, some dependencies cannot run on some python versions. We started with Python 3.6.0 but have since gone to versions 3.8, 3.9, and 3.10. Which one do we stick with?

**Comment by Phil-Barv** [comment]
@pabloguarneros I think we should stick to 3.6 as that's what we had started with.

**Comment by pabloguarneros** [comment]
Perfect, @Phil-Barv! I think Python 3.6.8 would do given it's the final bugfix release for Python 3.6.
